name: 'to-do-app'

services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: development
    restart: always
    environment:
      - PORT=3000
      - DATABASE_HOST=postgres_app
      - DATABASE_PASSWORD=ns
    ports:
      - "3000:3000"
    depends_on:
      - postgres_app
    volumes:
      - ./app:/son/app
      - /son/app/node_modules
    ## Development
    command: ["npm", "run", "start:dev"]
  postgres_app:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_PASSWORD=ns
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
    
  
    